version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: testedatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hono-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono-server
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://teste:teste@db:5432/testedatabase"
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    command: ["npm", "run", "dev"]

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
