version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: testedatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
